name = "the-cookie-jar-v1-reverse-proxy"  # Replace with your project name
compatibility_date = "2024-08-15"
main = "src/index.js"
account_id = "xxx"  # Replace with your Cloudflare account ID
[env.production]
name = "production"
workers_dev = false